# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Z:/mult_rom/mult_rom.cache/wt [current_project]
set_property parent.project_path Z:/mult_rom/mult_rom.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/mult_rom/mult_rom.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/agilo.ACAD.002/Desktop/mult_rom.coe
read_ip -quiet z:/mult_rom/mult_rom.srcs/sources_1/ip/mult_rom/mult_rom.xci
set_property used_in_implementation false [get_files -all z:/mult_rom/mult_rom.srcs/sources_1/ip/mult_rom/mult_rom_ooc.xdc]
set_property is_locked true [get_files z:/mult_rom/mult_rom.srcs/sources_1/ip/mult_rom/mult_rom.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top mult_rom -part xc7a35tcpg236-1


write_checkpoint -force -noxdef mult_rom.dcp

catch { report_utilization -file mult_rom_utilization_synth.rpt -pb mult_rom_utilization_synth.pb }
